<?php

/**
 * @file
 * Contains unitsapi.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function unitsapi_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the unitsapi module.
    case 'help.page.unitsapi':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('ConAPI module for converting distance, mass, and other units.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function unitsapi_theme() {
  $theme = [];

  return $theme;
}
